CREATE TABLE "cities" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"metro_id" uuid NOT NULL,
	"name" varchar(100) NOT NULL,
	"state_region" varchar(64) NOT NULL,
	"country_code" varchar(2) NOT NULL,
	"launch_status" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "cities_country_region_name_uq" UNIQUE("country_code","state_region","name"),
	CONSTRAINT "cities_id_metro_country_uq" UNIQUE("id","metro_id","country_code"),
	CONSTRAINT "cities_name_not_blank_ck" CHECK (length(btrim("cities"."name")) > 0),
	CONSTRAINT "cities_state_region_not_blank_ck" CHECK (length(btrim("cities"."state_region")) > 0),
	CONSTRAINT "cities_country_code_format_ck" CHECK ("cities"."country_code" ~ '^[A-Z]{2}$'),
	CONSTRAINT "cities_launch_status_ck" CHECK ("cities"."launch_status" IN ('ACTIVE','WAITLIST','FUTURE','DISABLED'))
);
--> statement-breakpoint
CREATE TABLE "metros" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"code" varchar(16) NOT NULL,
	"name" varchar(100) NOT NULL,
	"country_code" varchar(2) NOT NULL,
	"timezone" varchar(64) NOT NULL,
	"launch_status" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "metros_code_uq" UNIQUE("code"),
	CONSTRAINT "metros_id_country_uq" UNIQUE("id","country_code"),
	CONSTRAINT "metros_code_format_ck" CHECK ("metros"."code" ~ '^[A-Z][A-Z0-9_]{1,15}$'),
	CONSTRAINT "metros_name_not_blank_ck" CHECK (length(btrim("metros"."name")) > 0),
	CONSTRAINT "metros_country_code_format_ck" CHECK ("metros"."country_code" ~ '^[A-Z]{2}$'),
	CONSTRAINT "metros_timezone_not_blank_ck" CHECK (length(btrim("metros"."timezone")) > 0),
	CONSTRAINT "metros_launch_status_ck" CHECK ("metros"."launch_status" IN ('ACTIVE','WAITLIST','FUTURE','DISABLED'))
);
--> statement-breakpoint
CREATE TABLE "user_locations" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"city_id" uuid NOT NULL,
	"metro_id" uuid NOT NULL,
	"country_code" varchar(2) NOT NULL,
	"precision_type" text NOT NULL,
	"source" text NOT NULL,
	"captured_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_locations_precision_type_ck" CHECK ("user_locations"."precision_type" IN ('MANUAL_CITY')),
	CONSTRAINT "user_locations_source_ck" CHECK ("user_locations"."source" IN ('MANUAL'))
);
--> statement-breakpoint
ALTER TABLE "cities" ADD CONSTRAINT "cities_metro_country_fk" FOREIGN KEY ("metro_id","country_code") REFERENCES "public"."metros"("id","country_code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_locations" ADD CONSTRAINT "user_locations_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_locations" ADD CONSTRAINT "user_locations_city_metro_country_fk" FOREIGN KEY ("city_id","metro_id","country_code") REFERENCES "public"."cities"("id","metro_id","country_code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- MANUALLY ADDED (reviewed seed, not generated by drizzle-kit):
-- DATA-MODEL §23 example metro. DFW is seed data only, never a schema invariant.
INSERT INTO "metros" ("code", "name", "country_code", "timezone", "launch_status") VALUES
	('DFW', 'Dallas–Fort Worth', 'US', 'America/Chicago', 'ACTIVE');
--> statement-breakpoint
-- Owner-approved initial DFW taxonomy (PHASE-2-DECISIONS B4.1-D1). Further
-- cities require owner approval and a separate reviewed data migration.
INSERT INTO "cities" ("metro_id", "name", "state_region", "country_code", "launch_status")
SELECT m."id", c."name", 'TX', 'US', 'ACTIVE'
FROM "metros" m
CROSS JOIN (VALUES
	('Dallas'), ('Fort Worth'), ('Arlington'), ('Frisco'), ('Plano'), ('Irving'), ('McKinney'),
	('Allen'), ('Richardson'), ('Carrollton'), ('Coppell'), ('Prosper'), ('Denton'), ('Lewisville')
) AS c("name")
WHERE m."code" = 'DFW';
