CREATE TABLE "dating_consents" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"policy_version" varchar(40) NOT NULL,
	"source" text NOT NULL,
	"consented_at" timestamp with time zone NOT NULL,
	"revoked_at" timestamp with time zone,
	CONSTRAINT "dating_consents_source_ck" CHECK ("dating_consents"."source" IN ('ONBOARDING','SETTINGS','OTHER')),
	CONSTRAINT "dating_consents_policy_version_format_ck" CHECK ("dating_consents"."policy_version" ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,39}$'),
	CONSTRAINT "dating_consents_revoked_after_consented_ck" CHECK ("dating_consents"."revoked_at" IS NULL OR "dating_consents"."revoked_at" >= "dating_consents"."consented_at")
);
--> statement-breakpoint
CREATE TABLE "intent_options" (
	"code" text PRIMARY KEY NOT NULL,
	"parent_code" text,
	"label" varchar(60) NOT NULL,
	"description" varchar(160),
	"active" boolean DEFAULT true NOT NULL,
	"display_order" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "intent_options_code_format_ck" CHECK ("intent_options"."code" ~ '^[A-Z][A-Z_]{1,39}$'),
	CONSTRAINT "intent_options_not_own_parent_ck" CHECK ("intent_options"."parent_code" IS NULL OR "intent_options"."parent_code" <> "intent_options"."code"),
	CONSTRAINT "intent_options_label_not_blank_ck" CHECK (length(btrim("intent_options"."label")) > 0)
);
--> statement-breakpoint
CREATE TABLE "user_intents" (
	"user_id" uuid NOT NULL,
	"intent_code" text NOT NULL,
	"active" boolean NOT NULL,
	"selected_at" timestamp with time zone NOT NULL,
	"deselected_at" timestamp with time zone,
	CONSTRAINT "user_intents_pk" PRIMARY KEY("user_id","intent_code"),
	CONSTRAINT "user_intents_active_consistency_ck" CHECK ("user_intents"."active" = ("user_intents"."deselected_at" IS NULL)),
	CONSTRAINT "user_intents_deselected_after_selected_ck" CHECK ("user_intents"."deselected_at" IS NULL OR "user_intents"."deselected_at" >= "user_intents"."selected_at")
);
--> statement-breakpoint
ALTER TABLE "dating_consents" ADD CONSTRAINT "dating_consents_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "intent_options" ADD CONSTRAINT "intent_options_parent_code_intent_options_code_fk" FOREIGN KEY ("parent_code") REFERENCES "public"."intent_options"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_intents" ADD CONSTRAINT "user_intents_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_intents" ADD CONSTRAINT "user_intents_intent_code_intent_options_code_fk" FOREIGN KEY ("intent_code") REFERENCES "public"."intent_options"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "dating_consents_one_active_per_user_uq" ON "dating_consents" USING btree ("user_id") WHERE "dating_consents"."revoked_at" IS NULL;--> statement-breakpoint
-- MANUALLY ADDED (reviewed seed, not generated by drizzle-kit):
-- DATA-MODEL §17 / BR-INT-002. Top-level intents (shown on onboarding O04).
INSERT INTO "intent_options" ("code", "parent_code", "label", "description", "display_order") VALUES
	('FRIENDSHIP', NULL, 'Friendship', 'Meet new people and build genuine friendships.', 1),
	('ACTIVITIES', NULL, 'Activities', 'Find people to do things with nearby.', 2),
	('NETWORKING', NULL, 'Professional networking', 'Connect with people professionally.', 3),
	('DATING', NULL, 'Dating', 'Meet people who are also open to dating.', 4);
--> statement-breakpoint
-- Dating sub-intents: reference data only in B4.2A (not selectable; used by
-- the later Dating preferences flow).
INSERT INTO "intent_options" ("code", "parent_code", "label", "description", "display_order") VALUES
	('CASUAL_DATING', 'DATING', 'Casual dating', NULL, 1),
	('SERIOUS_RELATIONSHIP', 'DATING', 'Serious relationship', NULL, 2);
