CREATE TABLE "interest_categories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"code" text NOT NULL,
	"label" varchar(60) NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"display_order" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "interest_categories_code_uq" UNIQUE("code"),
	CONSTRAINT "interest_categories_code_format_ck" CHECK ("interest_categories"."code" ~ '^[A-Z][A-Z0-9_]{1,39}$'),
	CONSTRAINT "interest_categories_label_not_blank_ck" CHECK (length(btrim("interest_categories"."label")) > 0)
);
--> statement-breakpoint
CREATE TABLE "interests" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"code" text NOT NULL,
	"label" varchar(60) NOT NULL,
	"category_id" uuid NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"display_order" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "interests_code_uq" UNIQUE("code"),
	CONSTRAINT "interests_code_format_ck" CHECK ("interests"."code" ~ '^[A-Z][A-Z0-9_]{1,39}$'),
	CONSTRAINT "interests_label_not_blank_ck" CHECK (length(btrim("interests"."label")) > 0)
);
--> statement-breakpoint
CREATE TABLE "languages" (
	"code" text PRIMARY KEY NOT NULL,
	"display_name" varchar(60) NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"display_order" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "languages_code_format_ck" CHECK ("languages"."code" ~ '^[a-z]{2,3}$'),
	CONSTRAINT "languages_display_name_not_blank_ck" CHECK (length(btrim("languages"."display_name")) > 0)
);
--> statement-breakpoint
CREATE TABLE "user_interests" (
	"user_id" uuid NOT NULL,
	"interest_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_interests_pk" PRIMARY KEY("user_id","interest_id")
);
--> statement-breakpoint
CREATE TABLE "user_languages" (
	"user_id" uuid NOT NULL,
	"language_code" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_languages_pk" PRIMARY KEY("user_id","language_code")
);
--> statement-breakpoint
ALTER TABLE "interests" ADD CONSTRAINT "interests_category_id_interest_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."interest_categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_interests" ADD CONSTRAINT "user_interests_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_interests" ADD CONSTRAINT "user_interests_interest_id_interests_id_fk" FOREIGN KEY ("interest_id") REFERENCES "public"."interests"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_languages" ADD CONSTRAINT "user_languages_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_languages" ADD CONSTRAINT "user_languages_language_code_languages_code_fk" FOREIGN KEY ("language_code") REFERENCES "public"."languages"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- MANUALLY ADDED (reviewed seed, not generated by drizzle-kit):
-- PRD §17 / SFS O06 initial languages, in SFS display order (English first).
-- Codes are ISO 639-1.
INSERT INTO "languages" ("code", "display_name", "display_order") VALUES
	('en', 'English', 1),
	('te', 'Telugu', 2),
	('ta', 'Tamil', 3),
	('kn', 'Kannada', 4),
	('hi', 'Hindi', 5),
	('ml', 'Malayalam', 6),
	('gu', 'Gujarati', 7),
	('pa', 'Punjabi', 8),
	('bn', 'Bengali', 9),
	('mr', 'Marathi', 10),
	('ur', 'Urdu', 11),
	('or', 'Odia', 12);
--> statement-breakpoint
-- PRD §18 / DATA-MODEL §15 initial interest categories.
INSERT INTO "interest_categories" ("code", "label", "display_order") VALUES
	('SPORTS', 'Sports', 1),
	('ENTERTAINMENT', 'Entertainment', 2),
	('LIFESTYLE', 'Lifestyle', 3),
	('OUTDOORS', 'Outdoors', 4),
	('CULTURE', 'Culture', 5),
	('PROFESSIONAL', 'Professional', 6);
--> statement-breakpoint
-- PRD §18 initial interests (38), in PRD order within each category.
INSERT INTO "interests" ("code", "label", "category_id", "display_order")
SELECT i."code", i."label", c."id", i."display_order"
FROM (VALUES
	('SPORTS', 'CRICKET', 'Cricket', 1),
	('SPORTS', 'BADMINTON', 'Badminton', 2),
	('SPORTS', 'TENNIS', 'Tennis', 3),
	('SPORTS', 'PICKLEBALL', 'Pickleball', 4),
	('SPORTS', 'SOCCER', 'Soccer', 5),
	('SPORTS', 'BASKETBALL', 'Basketball', 6),
	('SPORTS', 'RUNNING', 'Running', 7),
	('SPORTS', 'GYM_FITNESS', 'Gym & fitness', 8),
	('ENTERTAINMENT', 'TELUGU_MOVIES', 'Telugu movies', 1),
	('ENTERTAINMENT', 'TAMIL_MOVIES', 'Tamil movies', 2),
	('ENTERTAINMENT', 'HINDI_MOVIES', 'Hindi movies', 3),
	('ENTERTAINMENT', 'KANNADA_MOVIES', 'Kannada movies', 4),
	('ENTERTAINMENT', 'HOLLYWOOD_MOVIES', 'Hollywood movies', 5),
	('ENTERTAINMENT', 'MUSIC', 'Music', 6),
	('ENTERTAINMENT', 'CONCERTS', 'Concerts', 7),
	('ENTERTAINMENT', 'STAND_UP_COMEDY', 'Stand-up comedy', 8),
	('LIFESTYLE', 'COFFEE', 'Coffee', 1),
	('LIFESTYLE', 'RESTAURANTS', 'Restaurants', 2),
	('LIFESTYLE', 'COOKING', 'Cooking', 3),
	('LIFESTYLE', 'TRAVEL', 'Travel', 4),
	('LIFESTYLE', 'PHOTOGRAPHY', 'Photography', 5),
	('LIFESTYLE', 'SHOPPING', 'Shopping', 6),
	('LIFESTYLE', 'ROAD_TRIPS', 'Road trips', 7),
	('OUTDOORS', 'HIKING', 'Hiking', 1),
	('OUTDOORS', 'CAMPING', 'Camping', 2),
	('OUTDOORS', 'CYCLING', 'Cycling', 3),
	('CULTURE', 'CLASSICAL_MUSIC', 'Classical music', 1),
	('CULTURE', 'CARNATIC_MUSIC', 'Carnatic music', 2),
	('CULTURE', 'BOLLYWOOD_DANCE', 'Bollywood dance', 3),
	('CULTURE', 'CLASSICAL_DANCE', 'Classical dance', 4),
	('CULTURE', 'FESTIVALS', 'Festivals', 5),
	('CULTURE', 'TEMPLES_CULTURAL_EVENTS', 'Temples & cultural events', 6),
	('PROFESSIONAL', 'TECHNOLOGY', 'Technology', 1),
	('PROFESSIONAL', 'ENTREPRENEURSHIP', 'Entrepreneurship', 2),
	('PROFESSIONAL', 'FINANCE', 'Finance', 3),
	('PROFESSIONAL', 'HEALTHCARE', 'Healthcare', 4),
	('PROFESSIONAL', 'CONSULTING', 'Consulting', 5),
	('PROFESSIONAL', 'STARTUPS', 'Startups', 6)
) AS i("category_code", "code", "label", "display_order")
JOIN "interest_categories" c ON c."code" = i."category_code";
